# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file './ui/ecc.ui'
#
# Created by: PyQt5 UI code generator 5.15.11
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets
import os
os.environ['QT_QPA_PLATFORM_PLUGIN_PATH']="../platforms"

class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(800, 600)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.label = QtWidgets.QLabel(self.centralwidget)
        self.label.setGeometry(QtCore.QRect(230, 20, 151, 51))
        font = QtGui.QFont()
        font.setPointSize(16)
        font.setBold(True)
        font.setWeight(75)
        self.label.setFont(font)
        self.label.setObjectName("label")
        self.keys_btn = QtWidgets.QToolButton(self.centralwidget)
        self.keys_btn.setGeometry(QtCore.QRect(400, 40, 91, 21))
        self.keys_btn.setObjectName("keys_btn")
        self.label_2 = QtWidgets.QLabel(self.centralwidget)
        self.label_2.setGeometry(QtCore.QRect(50, 90, 71, 21))
        self.label_2.setObjectName("label_2")
        self.label_3 = QtWidgets.QLabel(self.centralwidget)
        self.label_3.setGeometry(QtCore.QRect(50, 200, 71, 21))
        self.label_3.setObjectName("label_3")
        self.information_txt = QtWidgets.QPlainTextEdit(self.centralwidget)
        self.information_txt.setGeometry(QtCore.QRect(140, 70, 371, 81))
        self.information_txt.setObjectName("information_txt")
        self.signature_txt = QtWidgets.QPlainTextEdit(self.centralwidget)
        self.signature_txt.setGeometry(QtCore.QRect(140, 190, 371, 81))
        self.signature_txt.setObjectName("signature_txt")
        self.sign_btn = QtWidgets.QToolButton(self.centralwidget)
        self.sign_btn.setGeometry(QtCore.QRect(150, 310, 71, 21))
        self.sign_btn.setObjectName("sign_btn")
        self.verify_btn = QtWidgets.QToolButton(self.centralwidget)
        self.verify_btn.setGeometry(QtCore.QRect(440, 310, 71, 21))
        self.verify_btn.setObjectName("verify_btn")
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 800, 21))
        self.menubar.setObjectName("menubar")
        MainWindow.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
        self.label.setText(_translate("MainWindow", "ECC CIPHER"))
        self.keys_btn.setText(_translate("MainWindow", "Generate Keys"))
        self.label_2.setText(_translate("MainWindow", "Information:"))
        self.label_3.setText(_translate("MainWindow", "Signature:"))
        self.sign_btn.setText(_translate("MainWindow", "Sign"))
        self.verify_btn.setText(_translate("MainWindow", "Verify"))


if __name__ == "__main__":
    app = QtWidgets.QApplication(sys.argv)
    MainWindow = QtWidgets.QMainWindow()
    ui = Ui_MainWindow()
    ui.setupUi(MainWindow)
    MainWindow.show()
    sys.exit(app.exec_())