# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'ui\rsa.ui'
#
# Created by: PyQt5 UI code generator 5.15.11
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.
import os 
os.environ['QT_QPA_PLATFORM_PLUGIN_PATH'] = "../platforms"

from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(1603, 600)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.label = QtWidgets.QLabel(self.centralwidget)
        self.label.setGeometry(QtCore.QRect(360, 10, 161, 71))
        font = QtGui.QFont()
        font.setPointSize(18)
        font.setBold(True)
        font.setWeight(75)
        self.label.setFont(font)
        self.label.setObjectName("label")
        self.label_2 = QtWidgets.QLabel(self.centralwidget)
        self.label_2.setGeometry(QtCore.QRect(60, 80, 91, 31))
        font = QtGui.QFont()
        font.setPointSize(14)
        self.label_2.setFont(font)
        self.label_2.setObjectName("label_2")
        self.label_3 = QtWidgets.QLabel(self.centralwidget)
        self.label_3.setGeometry(QtCore.QRect(40, 150, 101, 31))
        font = QtGui.QFont()
        font.setPointSize(14)
        self.label_3.setFont(font)
        self.label_3.setObjectName("label_3")
        self.label_4 = QtWidgets.QLabel(self.centralwidget)
        self.label_4.setGeometry(QtCore.QRect(540, 80, 111, 31))
        font = QtGui.QFont()
        font.setPointSize(14)
        self.label_4.setFont(font)
        self.label_4.setObjectName("label_4")
        self.label_5 = QtWidgets.QLabel(self.centralwidget)
        self.label_5.setGeometry(QtCore.QRect(540, 150, 91, 31))
        font = QtGui.QFont()
        font.setPointSize(14)
        self.label_5.setFont(font)
        self.label_5.setObjectName("label_5")
        self.plaintext_txt = QtWidgets.QPlainTextEdit(self.centralwidget)
        self.plaintext_txt.setGeometry(QtCore.QRect(160, 70, 321, 61))
        self.plaintext_txt.setObjectName("plaintext_txt")
        self.ciphertext_txt = QtWidgets.QPlainTextEdit(self.centralwidget)
        self.ciphertext_txt.setGeometry(QtCore.QRect(160, 150, 321, 61))
        self.ciphertext_txt.setObjectName("ciphertext_txt")
        self.information_txt = QtWidgets.QPlainTextEdit(self.centralwidget)
        self.information_txt.setGeometry(QtCore.QRect(650, 70, 321, 61))
        self.information_txt.setObjectName("information_txt")
        self.signature_txt = QtWidgets.QPlainTextEdit(self.centralwidget)
        self.signature_txt.setGeometry(QtCore.QRect(650, 150, 321, 61))
        self.signature_txt.setObjectName("signature_txt")
        self.encrypt_btn = QtWidgets.QToolButton(self.centralwidget)
        self.encrypt_btn.setGeometry(QtCore.QRect(180, 270, 71, 21))
        self.encrypt_btn.setObjectName("encrypt_btn")
        self.decrypt_btn = QtWidgets.QToolButton(self.centralwidget)
        self.decrypt_btn.setGeometry(QtCore.QRect(350, 270, 71, 21))
        self.decrypt_btn.setObjectName("decrypt_btn")
        self.sign_btn = QtWidgets.QToolButton(self.centralwidget)
        self.sign_btn.setGeometry(QtCore.QRect(670, 280, 71, 21))
        self.sign_btn.setObjectName("sign_btn")
        self.verify_btn = QtWidgets.QToolButton(self.centralwidget)
        self.verify_btn.setGeometry(QtCore.QRect(850, 280, 71, 21))
        self.verify_btn.setObjectName("verify_btn")
        self.key_btn = QtWidgets.QToolButton(self.centralwidget)
        self.key_btn.setGeometry(QtCore.QRect(680, 20, 81, 21))
        self.key_btn.setObjectName("key_btn")
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 1603, 21))
        self.menubar.setObjectName("menubar")
        MainWindow.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
        self.label.setText(_translate("MainWindow", "RSA CIPHER"))
        self.label_2.setText(_translate("MainWindow", "Plain Text:"))
        self.label_3.setText(_translate("MainWindow", "Cipher Text:"))
        self.label_4.setText(_translate("MainWindow", "Information:"))
        self.label_5.setText(_translate("MainWindow", "Signature:"))
        self.encrypt_btn.setText(_translate("MainWindow", "Encrypt"))
        self.decrypt_btn.setText(_translate("MainWindow", "Decrypt"))
        self.sign_btn.setText(_translate("MainWindow", "Sign"))
        self.verify_btn.setText(_translate("MainWindow", "Verify"))
        self.key_btn.setText(_translate("MainWindow", "Generate Keys"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    MainWindow = QtWidgets.QMainWindow()
    ui = Ui_MainWindow()
    ui.setupUi(MainWindow)
    MainWindow.show()
    sys.exit(app.exec_())